[colors.bright]
black = "0x4C566A"
blue = "0x81A1C1"
cyan = "0x8FBCBB"
green = "0xA3BE8C"
magenta = "0xB48EAD"
red = "0xBF616A"
white = "0xECEFF4"
yellow = "0xEBCB8B"

[colors.normal]
black = "0x3B4252"
blue = "0x81A1C1"
cyan = "0x88C0D0"
green = "0xA3BE8C"
magenta = "0xB48EAD"
red = "0xBF616A"
white = "0xE5E9F0"
yellow = "0xEfcB80"

[colors.primary]
background = "0x2E3440"
foreground = "0xD8DEE9"

[font]
size = 12

[font.bold]
family = "UbuntuMono Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "UbuntuMono Nerd Font Mono"
style = "Bold Italic"

[font.italic]
family = "UbuntuMono Nerd Font Mono"
style = "Italic"

[font.normal]
family = "UbuntuMono Nerd Font Mono"
style = "Regular"

[font.offset]
x = 0
y = 0

# [[keyboard.bindings]]
# action = "Paste"
# key = "V"
# mode = "~Vi"
# mods = "Control|Shift"

# [[keyboard.bindings]]
# action = "Copy"
# key = "C"
# mods = "Control|Shift"

[keyboard]
bindings = [
    { key = "-", mods = "Control", action = "DecreaseFontSize" },
    { key = "+", mods = "Control | Shift", action = "IncreaseFontSize" },
    { key = "-", mods = "Alt", action = "ResetFontSize" },
]

[selection]
save_to_clipboard = true

[terminal.shell]
program = "/usr/bin/fish"

[window]
opacity = 0.90
