set -g window-style "fg=#dcd7ba,bg=#1f1f28"
set -g default-shell /usr/bin/fish
set -g pane-border-style "fg=#1f1f28 bg=#1f1f28"
set -g pane-active-border-style "fg=#555555 bg=#1f1f28"

# for VPS quirks
set -as terminal-features ',*:RGB'
set -g allow-passthrough on
set -ga update-environment TERM
set -ga update-environment TERM_PROGRAM
