# Keyd config must begin with [ids]
# [ids] is used to add/exclude devices
[ids]
*

-1d50:615e:0b4aa48d
-1d50:615e:3760fab9
-1d50:615e:c3d84a90

[global]
default_layout = graph
layer_indicator = 1
oneshot_timeout = 1000

[main]
capslock = overload(control, esc)
tab = overload(control, tab)
leftalt = oneshot(meta)
rightalt = oneshot(altgr)
sysrq = backspace
rightcontrol = backspace

leftmeta = layer(workspace)

delete = setlayout(main)
insert = setlayout(graph)

[altgr]
space = enter

[nav]
space = ,

j = left
k = down
l = up
; = right
h = esc
n = :

y = "
u = A-f
i = macro(8 down)
o = macro(8 up)
p = A-b

, = macro(down down down down)
. = macro(up up up up)
m = >
/ = <

leftmeta = layer(workspace_edit)

[sym]
capslock = !
q = #
w = [
e = ]
r = |
t = \
a = @
s = (
d = )
f = &
g = *
z = ^
x = {
c = }
v = $
b = ~

y = %
u = 7
i = 8
o = 9
p = .
h = _
j = 4
k = 5
l = 6
; = /
n = ;
m = 1
, = 2
. = 3
/ = 0
' = ?

rightalt = enter

[workspace]
leftshift = layer(workspace_edit)

/ = macro(leftmeta+0)
m = macro(leftmeta+1)
, = macro(leftmeta+2)
. = macro(leftmeta+3)
j = macro(leftmeta+4)
k = macro(leftmeta+5)
l = macro(leftmeta+6)
u = macro(leftmeta+7)
i = macro(leftmeta+8)
o = macro(leftmeta+9)

[workspace_edit]
/ = macro(leftmeta+leftshift+0)
m = macro(leftmeta+leftshift+1)
, = macro(leftmeta+leftshift+2)
. = macro(leftmeta+leftshift+3)
j = macro(leftmeta+leftshift+4)
k = macro(leftmeta+leftshift+5)
l = macro(leftmeta+leftshift+6)
u = macro(leftmeta+leftshift+7)
i = macro(leftmeta+leftshift+8)
o = macro(leftmeta+leftshift+9)

[graph:layout]
# enter = macro(leftshift+space)
[ = overload(graph_ctl, enter)
enter = macro(rightcontrol+leftshift+space)
space = lettermod(sym, space, 200, 200)
\ = macro(leftalt+leftcontrol) 
q = b
w = l
e = d
r = w
t = z
y = '
u = f
i = o
o = u
p = j
] = =
a = n
s = r
d = t
f = s
h = y
j = h
k = a
l = e
; = i
' = overload(graph_ctl, enter)
z = q
c = m
v = c
b = v
n = k
m = p
, = -
. = .
- = [
= = ]
/ = =

rightshift = graph_shift
leftshift = overload(nav, oneshot(graph_shift)) 
capslock = overload(graph_capslock, esc)
esc = oneshot(graph_shift)

# [graph_capslock:C]
# space = clearm(space)

[graph_ctl:C]
capslock = comma
# setting space to itself is needed to avoid locking up
# ctrl in non-modal (that is, the majority) text inputting
# contexts. Not using [graph_capslock:C] at all allows
# for the proper ctrl+space combo. Usability and consequences
# need to be further assessed
space = space

[graph_ctl_caps]
capslock = clearm(comma)

[graph_shift:S]
# space = togglem(graph_shift, space)
# capslock = togglem(graph_shift, esc)
# ' = overload(graph_ctl_caps, enter)

esc = sysrq
0 = :
b = V
l = E
d = T
w = L
z = Q
f = S
g = G
o = U
u = F
j = H
; = I
= = 
n = K
r = W
t = Z
s = R
y = `
h = Y
a = N
e = D
i = O
, = +
x = X
m = P
c = M
v = C
q = B
k = A
. = >
- = {
/ = <

# vim: ft=toml
