# Keyd config must begin with [ids]
# [ids] is used to add/exclude devices
[ids]
*

-1d50:615e:0b4aa48d
-1d50:615e:3760fab9
-1d50:615e:c3d84a90

[global]

[main]
capslock = overload(control, esc)
leftalt = leftmeta
rightalt = oneshot(alt)
leftmeta = layer(nav)
sysrq = backspace
rightcontrol = backspace
tab = overload(nav, tab)
# shift = oneshot(shift)

# temporary
pageup = setlayout(main)
pagedown = setlayout(graph)

[nav]
h = left
j = down
k = up
l = right
u = macro(8 down)
i = macro(8 up)
m = macro(down down down down)
, = macro(up up up up)

# Sym Layer (LH)
[sym]
#   # [ ] | ~
# ; @ ( ) & `
#   ^ { } $ \
# ---
q = #
w = [
e = ]
r = |
t = \
# ---
# capslock = ;
a = @
s = (
d = )
f = &
g = `
# ---
z = ^
x = {
c = }
v = $
b = ~

# Num Layer (RH)
[num]
#  % 7 8 9 *
#  + 4 5 6 = :
#  _ 1 2 3 0
# ---
y = %
u = 7
i = 8
o = 9
p = *
# ---
h = _
j = 4
k = 5
l = 6
; = =
' = !
# ---
n = !
m = 1
, = 2
. = 3
/ = 0

[graph:layout]
q = b
w = l
e = d
r = w
t = z
y = '
u = f
i = o
o = u
p = j
[ = ;
] = =
a = n
s = r
d = t
f = s
h = y
j = h
k = a
l = e
; = i
' = layer(graph_ctl)
z = lettermod(num, q, 200, 200)
c = m
v = c
b = v
n = k
m = p
, = -
. = .
- = [
= = ]
/ = lettermod(sym, /, 200, 200)
shift = overload(graph_shift, oneshot(graph_shift)) 
capslock = overload(graph_capslock, esc)

[graph_capslock:C]
' = enter
space = :

[graph_ctl:C]
space = comma
capslock = ;

[graph_shift:S]
b = V
l = E
d = T
w = L
z = Q
' = ?
f = S
g = G
o = U
u = F
j = H
; = I
= = 
n = K
r = W
t = Z
s = R
y = "
h = Y
a = N
e = D
i = O
, = +
x = X
m = P
c = M
v = C
q = B
k = A
. = >
- = {
/ = <
